[package]
name = "ar_dbg_client"
version = "0.2.0"
edition = "2021"
description = "Artosyn Register Trace Service Client"

[lints]
workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1.11"
thiserror = "2.0"
tracing = "0.1"
